# SQL settings
sql:
  # Supported types:
  # MySQL, SQLite, H2, PostgreSQL, MicrosoftSQL, Oracle,
  # Ingres, Informix, DB2, FrontBase, Firebird, Mongo,
  # mSQL, MaxDB
  type: sqlite
  # File name for file databases (sqlite, h2) database
  # name for hostname databases (mysql, postgresql, etc.)
  database: maussentials
  # Hostname and port only required for hostname databases.
  hostname: localhost
  port: 3306
# Message to show players on join
# Allowed variables:
# {PLAYER} = Player name
# {DISPLAYNAME} = Player display name
# {ONLINE} = Player count
# {MAXPLAYERS} = Max player count
welcome-message:
  - "&6Hello, &e{PLAYER}&6. There are &e{ONLINE} / {MAXPLAYERS}&6 players online."
  - "This is the second line of the message."