# There are some languages available by default.
#   Human-translated languages: en_US, fi_FI
#   Google-translated languages (slighty fixed using common sense): de_DE
#
# You can not override the languages available by default. If you want to modify them,
# rename the edited version to something else. Maussentials will always override all
# modifications to the default language files.
#
# If you make your own language file, make sure the extension is lang and the file is
# located in the language directory. Then put the name of the file without the extension
# in this field.
language: en_US
# SQL settings. Maussentials uses SQLibrary and supports all the database types that SQLibrary supports.
sql:
  # Supported types:
  # MySQL, SQLite, H2, PostgreSQL, MicrosoftSQL, Oracle,
  # Ingres, Informix, DB2, FrontBase, Firebird, Mongo,
  # mSQL, MaxDB.
  type: sqlite
  # File name for file databases (sqlite, h2)
  # Database name for hostname databases (mysql, postgresql, etc.) 
  database: maussentials
  # Hostname and port only required for hostname databases.
  hostname: localhost
  port: 3306

# Standard bans. Used with /sban <player> <default ban name>
# Set timeout to "permanent" for a permanent ban.
# Non-permanent timeouts can use any time/date units from milliseconds to years.
#   ms = milliseconds
#   s = seconds
#   m = minutes
#   h = hours
#   d = days
#   W = weeks
#   M = months
#   Y = years
# The units can be combined, for example "6d 4h 51m" = 6 days, 4 hours and 51 minutes.
# Overflow of units is also allowed. For example, "194m" = 194 minutes = 3 hours and 14 minutes.
standard-bans:
  hacks:
    timeout: permanent
    reason: Hacks
  spamming:
    timeout: 1W
    reason: Spamming in the chat