# Languages available by default: en_US, fi_FI

# If you make your own language file, make sure the extension is lang
# and the file is located in the language directory. Then put the name
# of the file without the extension in this field.
language: en_US
# SQL settings
sql:
  # Supported types:
  # MySQL, SQLite, H2, PostgreSQL, MicrosoftSQL, Oracle,
  # Ingres, Informix, DB2, FrontBase, Firebird, Mongo,
  # mSQL, MaxDB.
  type: sqlite
  # File name for file databases (sqlite, h2)
  # Database name for hostname databases (mysql, postgresql, etc.) 
  database: maussentials
  # Hostname and port only required for hostname databases.
  hostname: localhost
  port: 3306
# Message to show players on join
# Allowed variables:
# {PLAYER} = Player name
# {DISPLAYNAME} = Player display name
# {ONLINE} = Player count
# {MAXPLAYERS} = Max player count
# Format codes with & prefix
welcome-message:
  - "&6Hello, &e{PLAYER}&6. There are &e{ONLINE} / {MAXPLAYERS}&6 players online."
  - "This is the second line of the message."